heat_template_version: 2014-10-16

description: Template to deploy a single server with a python web app

parameters:
  key:
    type: string
    description: key name for outside connections
    default: poly_rsa

resources:

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: 'ext-net'

  web_server:
    type: 'OS::Nova::Server'
    properties:
      name: web_server
      image: INF4410-Ubuntu-trusty-mini
      flavor: INF4410-mini
      key_name: { get_param: key }
      networks:
        - network: cac571ab-8e5c-4332-8e05-4c69a56bda9e
        - network: 938775f1-1d27-4d35-a41d-e76eac6797db
      user_data: |
        #!/bin/bash
        wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
        chmod +x server.py
        exec python server.py

  server_floating_ip_association:
    type: 'OS::Nova::FloatingIPAssociation'
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: web_server }